<?php

/**
 * @file
 * Sample AJAX functionality so people can see some of the CTools AJAX
 * features in use.
 */

 //--------------
 // Drupal hooks.

 /**
  * Implements hook_menu().
  */
function ctools_ajax_sample_menu() {
  $items['ctools_ajax_sample'] = array(
    'title'           => 'Chaos Tools AJAX Demo',
    'page callback'   => 'ctools_ajax_sample_page',
    'access callback' => TRUE,
    'type'            => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Page callback to display links and render a container for AJAX stuff.
 */
function ctools_ajax_sample_page() {
  global $user;

  // Include the CTools tools that we need.
  ctools_include('ajax');
  ctools_include('modal');

  // Add CTools' javascript to the page.
  ctools_modal_add_js();

  // Create our own JavaScript that will be used to theme a modal.
  $sample_style = array(
    'ctools-sample-style' => array(
      'modalSize' => array(
        'type'      => 'fixed',
        'width'     => 500,
        'height'    => 300,
        'addWidth'  => 20,
        'addHeight' => 15,
      ),
      'modalOptions' => array(
        'opacity'          => .5,
        'background-color' => '#000',
      ),
      'animation'  => 'fadeIn',
      'modalTheme' => 'CToolsSampleModal',
      'throbber'   => theme('image', ctools_image_path('ajax-loader-gif', 'ctools_ajax_sample'), t('Loading...'), t('Loading')),
    ),
  );

  drupal_add_js($sample_style, 'setting');

  // Since we have our js, css and images in well-known named directories,
  // CTools makes it easy for us to just use them without worrying about
  // using drupal_get_path() and all that ugliness.
  ctools_add_js('ctools-ajax-sample', 'ctools_ajax_sample');
  ctools_add_css('ctools-ajax-sample', 'ctools_ajax_sample');

  $output = 'Hello from ctools_ajax_sample_page.';
  return $output;

}
